export const data = [
    { id: 1, translationStatus: 'new' },
    { id: 2, translationStatus: 'completed' },
    { id: 3, translationStatus: 'completed' },
    { id: 4, translationStatus: 'completed' },
    { id: 5, translationStatus: 'completed' },
    { id: 6, translationStatus: 'in progress' },
    { id: 7, translationStatus: 'in progress' },
    { id: 8, translationStatus: 'completed' },
    { id: 9, translationStatus: 'completed' },
    { id: 10, translationStatus: 'completed' },
    { id: 11, translationStatus: 'completed' },
    { id: 12, translationStatus: 'completed' },
    { id: 13, translationStatus: 'completed' },
    { id: 14, translationStatus: 'completed' },
    { id: 15, translationStatus: 'completed' },
    { id: 16, translationStatus: 'completed' },
    { id: 17, translationStatus: 'completed' },
]